version: "3"

services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - type: bind
        source: .
        target: /usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true